// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupBa4_sCup9c7zBjABRgLBNP4_A4WHXs',
    appId: '1:1014905004323:web:822006dfe77ffc0dfe6c96',
    messagingSenderId: '1014905004323',
    projectId: 'docdoc-a5f0d',
    authDomain: 'docdoc-a5f0d.firebaseapp.com',
    storageBucket: 'docdoc-a5f0d.firebasestorage.app',
    measurementId: 'G-STL94J8643',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBraaZcYp7fa-EVvMKgkeeZ1-OnmEVQMOI',
    appId: '1:1014905004323:android:bfe534b3b6b3b3befe6c96',
    messagingSenderId: '1014905004323',
    projectId: 'docdoc-a5f0d',
    storageBucket: 'docdoc-a5f0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd1M0AP72vf716ejkXmQieZvuz6d5bbuQ',
    appId: '1:1014905004323:ios:35c992209061d1b3fe6c96',
    messagingSenderId: '1014905004323',
    projectId: 'docdoc-a5f0d',
    storageBucket: 'docdoc-a5f0d.firebasestorage.app',
    iosBundleId: 'com.example.docdocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd1M0AP72vf716ejkXmQieZvuz6d5bbuQ',
    appId: '1:1014905004323:ios:35c992209061d1b3fe6c96',
    messagingSenderId: '1014905004323',
    projectId: 'docdoc-a5f0d',
    storageBucket: 'docdoc-a5f0d.firebasestorage.app',
    iosBundleId: 'com.example.docdocApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBupBa4_sCup9c7zBjABRgLBNP4_A4WHXs',
    appId: '1:1014905004323:web:76f32817a5bdba76fe6c96',
    messagingSenderId: '1014905004323',
    projectId: 'docdoc-a5f0d',
    authDomain: 'docdoc-a5f0d.firebaseapp.com',
    storageBucket: 'docdoc-a5f0d.firebasestorage.app',
    measurementId: 'G-F9GBXZWN7H',
  );
}
